title: akycs97
subtitle: Student of M.Tech(Artificial Intellegence) at IISc.
name: Akhilesh Yadav
description: >- # this means to ignore newlines until "baseurl:"
  #Student of M.Tech(Artificial Intellegence) at IISc.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    #- #text: Shop
      #url : /shopAbout
    - text: Contact Me
      url : /contact
    #- text: Styleguide
      #url: /styleguide
    #- text: Get Started
      #url: /get-started

# Edit these details

author_logo: profile.png
author: Akhilesh Yadav
author_bio: Hello, My Name is Akhilesh Yadav I love to desing robust and scalable code for machine learning.
author_email: "akhilesh20yadav12@gmail.com"
author_location: India
author_website_url: "akhileshyadav12.github.io"

author_work_experiences:
            - company_name: ETL_LAB, Lucknow
              company_logo: etl.png
              company_url: https://etllearninghub.com/
              designation: Intern Data Analytics
              description: Worked on IPL Data
              visibility: true
            # - company_name: Microsoft
            #   company_logo: microsoft.png
            #   company_url: https://microsoft.com
            #   designation: Azure Developer
            #   description: Worked on various Azure Cloud Products
            #   visibility: true

author_education_details:
              - college_logo: IIScLogo.png
                college_name: Indian Institute of Science, Bangaluru
                college_url: https://iisc.ac.in
                college_degree: Artificial Intelligence
                description: Master of Technology
                visibility: true
              - college_logo: srmcemlogo.png
                college_name: Shri Ramswaroop Memorial Group of Professional College, Lucknow
                college_url: https://srmcem.ac.in
                college_degree: Computer Science & Engineering
                description: Batchelor of Technology
                visibility: true
              - college_logo: uplogo.jpg
                college_name: Udai Pratap Inter College,Varanasi
                college_url: http://www.upcollege.org/
                college_degree: Intermediate
                description: Pysics, Chemistry, Math
                visibility: true

# author_project_details:
#               - project_thumbnail: gamershub.png
#                 project_title: Gamers Hub
#                 project_description: A Platform built for Gamers and Game Devs
#                 project_url: https://gamershub.in
#                 visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: Akhilesh Yadav
github_username:  akhileshyadav12
facebook_username: Akhilesh Yadav
linkedin_username: Akhilesh Yadav
behance_username: Akhilesh Yadav
instagram_username: Akhilesh Yadav
medium_username: Akhilesh Yadav
telegram_username: Akhilesh Yadav
dribbble_username: Akhilesh Yadav
flickr_username: Akhilesh Yadav

# #for comments using disqus
# disqus_shortname: sujay-kundu

# # wakatime username (coding activity)
# wakatime_username: akhileshyadav12

mailchimp embedded form url (newsletter):
mailchimp_form_url: https://formspree.io/xyyjzdkj
# formspree (contact form)
formspree_email: xdozklkk

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# # algolia search
# algolia:
#   application_id: D9WA1YKTRQ
#   index_name: blog_posts # You can replace that with whatever name you want
#   files_to_exclude: []
#   nodes_to_index: 'article'
#   search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

#search: false

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build